### ISSUE TITLE
use case modeling and documentation

### ISSUE THREAD

**Issue by riddhitanna** [riddhitanna/AQI-Analytics-Dashboard-32#4]

**Comment by Jack-2001** [comment]
![Use_Case](https://user-images.githubusercontent.com/73009107/113475436-590c1700-9493-11eb-9dab-15c99649830d.png)
Here is the use case diagram for the Library Management system

And here goes the description for the issue book

Description of “Issue Book”
Actors: Librarian, Student
1.	Student wants to issue a book
a.	Login to the system
b.	Will search for a book
c.	Visit Librarian
2.	Librarian will do the process of Book
a.	Issue book and mark due date
b.	It includes that librarian needs to check whether student is valid or not
c.	It includes that librarian needs to check whether the book is available or not
